export const SERVICE_CATEGORIES = [
  { id: 'barman', label: 'Barman', icon: '🍹' },
  { id: 'servicos-gerais', label: 'Serviços Gerais', icon: '🔧' },
  { id: 'faxina', label: 'Faxina', icon: '🧹' },
  { id: 'limpeza-piscina', label: 'Limpeza de Piscina', icon: '🏊' },
  { id: 'pedreiro', label: 'Pedreiro', icon: '🧱' },
  { id: 'manicure', label: 'Manicure', icon: '💅' },
  { id: 'encanador', label: 'Encanador', icon: '🔩' },
  { id: 'garcom', label: 'Garçom', icon: '🍽️' },
  { id: 'borracheiro', label: 'Borracheiro', icon: '🔄' },
  { id: 'jardineiro', label: 'Jardineiro', icon: '🌿' },
  { id: 'vigia', label: 'Vigia', icon: '👁️' },
  { id: 'cumim', label: 'Cumim', icon: '🛎️' },
  { id: 'ajudante-obra', label: 'Ajudante de Obra', icon: '👷' },
  { id: 'motorista', label: 'Motorista', icon: '🚗' },
  { id: 'desentupidor', label: 'Desentupidor', icon: '🚿' },
  { id: 'dedetizacao', label: 'Dedetização', icon: '🐛' },
  { id: 'refrigeracao', label: 'Refrigeração', icon: '❄️' },
  { id: 'advogado', label: 'Advogado', icon: '⚖️' },
  { id: 'contador', label: 'Contador', icon: '📊' },
  { id: 'pintor', label: 'Pintor', icon: '🎨' },
  { id: 'gesseiro', label: 'Gesseiro', icon: '🏗️' },
  { id: 'chapa', label: 'Chapa', icon: '📦' },
  { id: 'chapeiro', label: 'Chapeiro', icon: '🍔' },
  { id: 'cozinheira', label: 'Cozinheira', icon: '👩‍🍳' },
  { id: 'auxiliar-cozinha', label: 'Auxiliar de Cozinha', icon: '🥘' },
  { id: 'motoboy', label: 'Motoboy', icon: '🏍️' },
  { id: 'embalador', label: 'Embalador', icon: '📦' },
  { id: 'acougueiro', label: 'Açougueiro', icon: '🥩' },
  { id: 'repositor', label: 'Repositor', icon: '🏪' },
  { id: 'operador-caixa', label: 'Operador de Caixa', icon: '💰' },
]
